import { test, expect, APIRequestContext, APIResponse } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { rm } from 'node:fs/promises';
import path from 'node:path';
import { localTestData } from '../helpers/test-data';
const API = process.env.E2E_API_URL ?? 'http://localhost:3001';
async function ok(response: APIResponse) { expect(response.ok(), await response.text()).toBe(true); return response.json(); }
async function fixture(request: APIRequestContext) {
  const data = localTestData();
  if (process.env.S3_BUCKET?.trim()) { await data.cleanup(); throw new Error('Workroom tests require local file storage'); }
  const submissionIds: string[] = [];
  try {
    const auth = await ok(await request.post(`${API}/auth/register`, { data: { firmName: data.firmName, firstName: 'Portal', lastName: 'Lawyer', email: data.email, password: data.password } }));
    const headers = { Authorization: `Bearer ${auth.accessToken}` };
    const client = await data.db.client.create({ data: { firmId: auth.user.firmId, name: data.tag } });
    const passwordHash = (await data.db.user.findUniqueOrThrow({ where: { id: auth.user.id } })).passwordHash;
    async function contact(name: string, clientId = client.id) {
      const row = await data.db.clientContact.create({ data: { clientId, name, email: `${data.tag}-${name}@example.test`, passwordHash, portalEnabled: true } });
      const session = await ok(await request.post(`${API}/client-portal/auth/login`, { data: { email: row.email, password: data.password } }));
      return { ...row, token: session.accessToken, headers: { Authorization: `Bearer ${session.accessToken}` } };
    }
    const original = await contact('original'); const replacement = await contact('replacement');
    async function submission(title: string) {
      const row = await ok(await request.post(`${API}/client-portal/intake`, { headers: original.headers, multipart: { title, detail: 'Local fixture request', files: { name: 'original.txt', mimeType: 'text/plain', buffer: Buffer.from('original attachment') } } }));
      submissionIds.push(row.id);
      return row;
    }
    const room = await submission(`Workroom ${data.tag}`); const unrelated = await submission(`Unrelated ${data.tag}`);
    const intake = await data.db.intake.create({ data: { firmId: auth.user.firmId, receivedById: auth.user.id, clientId: client.id, title: room.title } });
    await data.db.portalIntakeSubmission.update({ where: { id: room.id }, data: { intakeId: intake.id } });
    const internal = await data.db.document.create({ data: { intakeId: intake.id, filename: 'internal-secret.txt', mimeType: 'text/plain', storagePath: 'never-download-internal-fixture', uploadedById: auth.user.id, visibleToClient: false } });
    return { ...data, auth, headers, original, replacement, room, unrelated, internal, contact,
      async cleanup() {
        // Remove only directories generated by this fixture; database cascades clean rows.
        const root = path.resolve('apps/api', process.env.UPLOAD_DIR ?? './uploads');
        for (const id of submissionIds) for (const folder of ['portal-intake', 'portal-workroom']) await rm(path.join(root, folder, id), { recursive: true, force: true });
        await data.cleanup();
      },
    };
  } catch (error) { await data.cleanup(); throw error; }
}

test('workroom agreements, concurrent upload retries, bytes, tenant scope and selected-request contact replacement', async ({ request, page }) => {
  test.setTimeout(120000);
  const f = await fixture(request); const other = await fixture(request);
  try {
    const staff = `${API}/portal-workroom/${f.room.id}`;
    const portal = `${API}/client-portal/workroom/${f.room.id}`;
    const legacy = `${API}/client-portal/intake/${f.room.id}`;
    const bytes = Buffer.from('Client evidence bytes — ข้อเท็จจริง');
    const requestKey = randomUUID();
    const send = () => request.post(`${portal}/messages`, { headers: f.original.headers, multipart: { requestKey, body: 'Client evidence', file: { name: 'evidence.txt', mimeType: 'text/plain', buffer: bytes } } });
    const sent = await Promise.all([send(), send()]);
    const responses = await Promise.all(sent.map(ok));
    expect(responses[0].id).toBe(responses[1].id);
    expect(responses.filter(r => r.duplicate)).toHaveLength(1);
    expect((await ok(await send())).id).toBe(responses[0].id);
    expect((await request.post(`${portal}/messages`, { headers: f.original.headers, multipart: { requestKey, body: 'Changed body', file: { name: 'evidence.txt', mimeType: 'text/plain', buffer: bytes } } })).status()).toBe(409);
    const downloaded = await request.get(`${staff}/files/${responses[0].id}`, { headers: f.headers });
    expect(downloaded.status()).toBe(200); expect(await downloaded.body()).toEqual(bytes);
    expect(downloaded.headers()['x-content-type-options']).toBe('nosniff');
    const proposal = { version: 0, scopeText: 'Review evidence and deliver written advice', proposedDate: '2026-12-15T00:00:00.000Z' };
    await ok(await request.post(`${staff}/proposal`, { headers: f.headers, data: proposal }));
    expect((await request.post(`${staff}/proposal`, { headers: f.headers, data: proposal })).status()).toBe(409);
    expect((await request.post(`${portal}/accept`, { headers: f.original.headers, data: { version: 0 } })).status()).toBe(409);
    await ok(await request.post(`${portal}/accept`, { headers: f.original.headers, data: { version: 1 } }));
    await ok(await request.post(`${portal}/accept`, { headers: f.original.headers, data: { version: 1 } }));
    const advice = Buffer.from('Delivered advice');
    const deliverable = await ok(await request.post(`${staff}/messages`, { headers: f.headers, multipart: { requestKey: randomUUID(), body: 'Final advice for accepted scope', file: { name: 'advice.txt', mimeType: 'text/plain', buffer: advice } } }));
    const adviceResponse = await request.get(`${portal}/files/${deliverable.id}`, { headers: f.original.headers });
    expect(adviceResponse.status()).toBe(200); expect(await adviceResponse.body()).toEqual(advice);
    await ok(await request.post(`${staff}/deliver`, { headers: f.headers, data: { messageId: deliverable.id } }));
    await ok(await request.post(`${portal}/acknowledge-delivery`, { headers: f.original.headers, data: { version: 1 } }));
    expect((await ok(await request.get(portal, { headers: f.original.headers }))).deliveryAcknowledgedAt).toBeTruthy();

    // Exercise the actual client composer with its authenticated portal session.
    await page.addInitScript(token => localStorage.setItem('lawfirm_portal_access_token', token), f.original.token);
    await page.goto(`http://localhost:3005/portal/intake/${f.room.id}`);
    const workroom = page.locator('section').filter({ has: page.getByRole('heading', { name: /ห้องทำงานร่วมกัน|Shared workroom/ }) });
    await expect(workroom).toBeVisible();
    await workroom.locator('textarea').first().fill(`Browser message ${f.tag}`);
    await workroom.getByRole('button', { name: /ส่งข้อความและไฟล์|Send message and file/ }).click();
    await expect(workroom.getByText(`Browser message ${f.tag}`, { exact: true })).toBeVisible();

    const staffOrigin = `http://${f.auth.user.firmSlug}.localhost:3005`;
    const handoff = new URLSearchParams({ access_token: f.auth.accessToken, refresh_token: f.auth.refreshToken, next: '/intake/portal-submissions', locale: 'en' });
    await page.goto(`${staffOrigin}/handoff#${handoff}`);
    await expect(page).toHaveURL(`${staffOrigin}/intake/portal-submissions`);
    await page.getByRole('combobox').first().selectOption(f.room.id);
    await expect(page.getByRole('heading', { name: /ห้องทำงานร่วมกัน|Shared workroom/ })).toBeVisible();
    await expect(page.getByText(`Browser message ${f.tag}`, { exact: true })).toBeVisible();
    await page.screenshot({ path: 'e2e/shots/portal-workroom-staff.png', fullPage: true });

    expect((await request.get(staff, { headers: other.headers })).status()).toBe(404);
    expect((await request.get(portal, { headers: other.original.headers })).status()).toBe(404);
    const alienClient = await f.db.client.create({ data: { firmId: f.auth.user.firmId, name: 'Other client' } });
    const alienContact = await f.contact('alien', alienClient.id);
    expect((await request.post(`${staff}/handover`, { headers: f.headers, data: { fromContactId: f.original.id, toContactId: alienContact.id } })).status()).toBe(400);
    const legacyData = await ok(await request.get(legacy, { headers: f.original.headers }));
    const attachmentId = legacyData.attachments[0].id;
    await ok(await request.post(`${staff}/handover`, { headers: f.headers, data: { fromContactId: f.original.id, toContactId: f.replacement.id } }));
    for (const url of [portal, `${portal}/files/${deliverable.id}`, legacy, `${legacy}/attachments/${attachmentId}/download`, `${legacy}/firm-documents/${f.internal.id}/download`]) expect((await request.get(url, { headers: f.original.headers })).status(), url).toBe(404);
    expect((await request.post(`${portal}/messages`, { headers: f.original.headers, data: { requestKey: randomUUID(), body: 'Revoked' } })).status()).toBe(404);
    await ok(await request.get(portal, { headers: f.replacement.headers }));
    expect((await request.get(`${API}/client-portal/workroom/${f.unrelated.id}`, { headers: f.replacement.headers })).status()).toBe(404);
    const replacementData = await ok(await request.get(legacy, { headers: f.replacement.headers }));
    expect(replacementData.firmDocuments).toEqual([]);
    expect((await request.get(`${legacy}/firm-documents/${f.internal.id}/download`, { headers: f.replacement.headers })).status()).toBe(404);
    const sharedAttachment = await request.get(`${legacy}/attachments/${attachmentId}/download`, { headers: f.replacement.headers });
    expect(sharedAttachment.status()).toBe(200); expect(await sharedAttachment.body()).toEqual(Buffer.from('original attachment'));
    const sharedDelivery = await request.get(`${portal}/files/${deliverable.id}`, { headers: f.replacement.headers });
    expect(sharedDelivery.status()).toBe(200); expect(await sharedDelivery.body()).toEqual(advice);
    const mine = await ok(await request.get(`${API}/client-portal/intake`, { headers: f.replacement.headers }));
    expect(mine.map((r: { id: string }) => r.id)).toEqual([f.room.id]);
  } finally { await other.cleanup(); await f.cleanup(); }
});
