import { test, expect } from '@playwright/test';
import { localTestData } from '../helpers/test-data';
import { FEE_MAX } from '@lawfirm/shared';

const API = process.env.E2E_API_URL ?? 'http://localhost:3001';

for (const width of [375, 1440]) {
  test(`short forms save real data and preserve validation at ${width}px`, async ({ page, request }, testInfo) => {
    const data = localTestData();
    try {
      const response = await request.post(`${API}/auth/register`, { data: {
        firmName: data.firmName, firstName: 'ทดสอบ', lastName: 'ฟอร์ม', email: data.email, password: data.password,
      } });
      expect(response.status()).toBe(201);
      const auth = await response.json();
      const origin = `http://${auth.user.firmSlug}.localhost:3005`;
      await page.setViewportSize({ width, height: 900 });
      const hash = new URLSearchParams({ access_token: auth.accessToken, refresh_token: auth.refreshToken, next: '/cases/new', locale: 'th' });
      await page.goto(`${origin}/handoff#${hash}`);
      await expect(page).toHaveURL(`${origin}/cases/new`);
      const tour = page.getByRole('button', { name: 'ปิดคำแนะนำ', exact: true });
      if (await tour.isVisible()) await tour.click();
      await page.locator('#case-type').selectOption({ label: 'คดีอาญา' });
      const charge = page.getByRole('textbox', { name: 'ข้อหาหรือฐานความผิด *', exact: true });
      await expect(charge).toBeVisible();
      await page.getByRole('button', { name: 'สร้างคดี', exact: true }).click();
      expect(await charge.evaluate((el: HTMLTextAreaElement) => el.validity.valueMissing)).toBe(true);
      await expect(page).toHaveURL(`${origin}/cases/new`);
      await page.locator('#case-type').selectOption({ label: 'คดีความ' });
      await expect(charge).toHaveCount(0);
      const details = page.getByText('รายละเอียดคดีเพิ่มเติม (ไม่บังคับ)', { exact: true });
      const amount = page.getByRole('textbox', { name: 'ทุนทรัพย์ที่เรียกร้อง (บาท)', exact: true });
      await expect(amount).toBeHidden();
      await details.click();
      await amount.fill(String(FEE_MAX + 1));
      await details.click();
      await page.getByRole('button', { name: 'สร้างคดี', exact: true }).click();
      await expect(amount).toBeVisible();
      expect(await amount.evaluate((el: HTMLInputElement) => el.checkValidity())).toBe(false);
      await amount.fill('25000');
      await page.getByRole('textbox', { name: 'ศาล', exact: true }).fill('ศาลทดสอบ');
      await details.click();
      await page.getByRole('textbox', { name: 'ชื่อคดี *', exact: true }).fill(`คดีฟอร์มสั้น ${data.tag}`);
      await expect(page.locator('#lead-lawyer')).toHaveValue(auth.user.id);
      expect(await page.locator('main input, main select, main textarea').evaluateAll(elements => elements.filter(el => !el.closest('details:not([open])') && el.getClientRects().length > 0).length)).toBe(4);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await testInfo.attach(`case-${width}`, { body: await page.screenshot({ fullPage: true }), contentType: 'image/png' });
      await page.getByRole('button', { name: 'สร้างคดี', exact: true }).click();
      await expect(page).toHaveURL(/\/cases\/[0-9a-f-]+\?tab=tasks/);
      const legalCase = await data.db.case.findFirstOrThrow({ where: { firmId: auth.user.firmId } });
      expect(legalCase.title).toBe(`คดีฟอร์มสั้น ${data.tag}`);
      expect(Number(legalCase.claimedAmount)).toBe(25000);
      expect(legalCase.courtName).toBe('ศาลทดสอบ');

      await page.goto(`${origin}/clients/new`);
      if (await tour.isVisible()) await tour.click();
      await page.getByRole('combobox', { name: 'ประเภท', exact: true }).selectOption('COMPANY');
      await page.getByRole('textbox', { name: 'ชื่อบริษัท *', exact: true }).fill(`บริษัท ${data.tag}`);
      await expect(page.getByRole('textbox', { name: 'ชื่อผู้ติดต่อ 1', exact: true })).toBeHidden();
      await page.getByRole('button', { name: 'บันทึกลูกค้า', exact: true }).click();
      await expect(page).toHaveURL(/\/clients\?id=/);
      const client = await data.db.client.findFirstOrThrow({ where: { firmId: auth.user.firmId, name: `บริษัท ${data.tag}` }, include: { contacts: true } });
      expect(client.type).toBe('COMPANY');
      expect(client.contacts).toHaveLength(1);

      await page.goto(`${origin}/clients/new`);
      if (await tour.isVisible()) await tour.click();
      await page.getByRole('combobox', { name: 'ประเภท', exact: true }).selectOption('COMPANY');
      await page.getByRole('textbox', { name: 'ชื่อบริษัท *', exact: true }).fill(`บริษัทพร้อมผู้ติดต่อ ${data.tag}`);
      const contacts = page.getByText('ผู้ติดต่อ · ไม่บังคับ', { exact: true });
      await contacts.click();
      const email = page.getByRole('textbox', { name: 'อีเมล 1', exact: true });
      const phone = page.getByRole('textbox', { name: 'โทรศัพท์ 1', exact: true });
      await email.fill('wrong-email');
      await phone.fill('not-a-phone');
      await contacts.click();
      await page.getByRole('button', { name: 'บันทึกลูกค้า', exact: true }).click();
      await expect(email).toBeVisible();
      expect(await email.evaluate((el: HTMLInputElement) => el.validity.typeMismatch)).toBe(true);
      expect(await phone.evaluate((el: HTMLInputElement) => el.validity.patternMismatch)).toBe(true);
      await email.fill('contact@example.test');
      await phone.fill('081-234-5678');
      await page.getByRole('button', { name: 'บันทึกลูกค้า', exact: true }).click();
      const contactName = page.getByRole('textbox', { name: 'ชื่อผู้ติดต่อ 1', exact: true });
      expect(await contactName.evaluate((el: HTMLInputElement) => el.validity.valueMissing)).toBe(true);
      await expect(page).toHaveURL(`${origin}/clients/new`);
      await expect(email).toHaveValue('contact@example.test');
      await contactName.fill('   ');
      await contacts.click();
      await page.getByRole('button', { name: 'บันทึกลูกค้า', exact: true }).click();
      await expect(contactName).toBeVisible();
      expect(await contactName.evaluate((el: HTMLInputElement) => el.validity.patternMismatch)).toBe(true);
      await contactName.fill('ผู้ติดต่อทดสอบ');
      await contacts.click();
      await page.getByRole('button', { name: 'บันทึกลูกค้า', exact: true }).click();
      await expect(page).toHaveURL(/\/clients\?id=/);
      const completeClient = await data.db.client.findFirstOrThrow({ where: { firmId: auth.user.firmId, name: `บริษัทพร้อมผู้ติดต่อ ${data.tag}` }, include: { contacts: true } });
      expect(completeClient.contacts[0]).toMatchObject({ name: 'ผู้ติดต่อทดสอบ', email: 'contact@example.test', phone: '081-234-5678' });

      await page.goto(`${origin}/operations`);
      if (await tour.isVisible()) await tour.click();
      await page.getByRole('button', { name: 'ต้องจัดการวันนี้', exact: true }).click();
      await page.getByRole('button', { name: 'เพิ่มงาน', exact: true }).click();
      const dialog = page.getByRole('dialog', { name: 'เพิ่มงานใหม่', exact: true });
      await dialog.getByRole('textbox', { name: 'ชื่องาน', exact: true }).fill(`งานฟอร์มสั้น ${data.tag}`);
      await expect(dialog.getByRole('combobox', { name: 'ขนาดงาน', exact: true })).toBeHidden();
      expect(await dialog.locator('input, select, textarea').evaluateAll(elements => elements.filter(el => !el.closest('details:not([open])') && el.getClientRects().length > 0).length)).toBe(3);
      await dialog.getByRole('button', { name: 'สร้างงาน', exact: true }).click();
      await expect(dialog).toHaveCount(0);
      await expect(page.getByRole('button', { name: `งานฟอร์มสั้น ${data.tag}`, exact: true })).toBeVisible();
      await page.reload();
      await page.getByRole('button', { name: 'ต้องจัดการวันนี้', exact: true }).click();
      await expect(page.getByRole('button', { name: `งานฟอร์มสั้น ${data.tag}`, exact: true })).toBeVisible();
      await page.getByRole('button', { name: 'เพิ่มงาน', exact: true }).click();
      await dialog.getByRole('textbox', { name: 'ชื่องาน', exact: true }).fill(`งานพร้อมรายละเอียด ${data.tag}`);
      await dialog.getByRole('combobox', { name: 'ผู้รับผิดชอบ', exact: true }).selectOption(auth.user.id);
      await expect(dialog.getByRole('button', { name: 'สร้างงาน', exact: true })).toBeDisabled();
      await dialog.getByRole('checkbox', { name: 'รับทราบข้อมูลและยืนยันการจัดงานนี้', exact: true }).check();
      await expect(dialog.getByRole('button', { name: 'สร้างงาน', exact: true })).toBeEnabled();
      await dialog.getByRole('combobox', { name: 'ผู้รับผิดชอบ', exact: true }).selectOption('');
      const advanced = dialog.getByText('รายละเอียด / กำหนดส่ง / การจัดคิว', { exact: true });
      await advanced.click();
      await dialog.getByRole('textbox', { name: 'รายละเอียด / ผลงานที่ต้องส่ง', exact: true }).fill('ส่งเอกสารครบ');
      await dialog.getByRole('combobox', { name: 'ขนาดงาน', exact: true }).selectOption('L');
      await dialog.getByRole('combobox', { name: 'ตรวจงานก่อนเสร็จ', exact: true }).selectOption('YES');
      await dialog.locator('summary').click();
      await dialog.getByRole('button', { name: 'สร้างงาน', exact: true }).click();
      await expect(dialog.getByRole('combobox', { name: 'ผู้ตรวจ', exact: true })).toBeVisible();
      await dialog.getByRole('combobox', { name: 'ผู้ตรวจ', exact: true }).selectOption(auth.user.id);
      await dialog.locator('summary').click();
      await dialog.getByRole('button', { name: 'สร้างงาน', exact: true }).click();
      await expect(dialog).toHaveCount(0);
      const task = await data.db.task.findFirstOrThrow({ where: { createdById: auth.user.id, title: `งานพร้อมรายละเอียด ${data.tag}` } });
      expect(task.description).toBe('ส่งเอกสารครบ');
      expect(task.size).toBe('L');
      expect(task.requiresReview).toBe(true);
      expect(task.reviewerId).toBe(auth.user.id);
    } finally { await data.cleanup(); }
  });
}
