'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/lib/auth';
import { useLocale } from '@/components/landing/LocaleProvider';
import { PlaybookRelease, PlaybookStep, setupRequest } from '@/lib/practice-setup';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
const starters: Record<string, [string, PlaybookStep[]]> = {
  GENERAL: ['เตรียมและติดตามคดี', [{ title: 'ตรวจขอบเขตงานและผู้รับผิดชอบ', days: 0, kind: 'TASK', instructions: 'ตรวจข้อตกลงก่อนเริ่มงานและกำหนดผู้รับผิดชอบแต่ละขั้น' }, { title: 'รวบรวมเอกสารต้นฉบับ', days: 1, kind: 'DOCUMENT', instructions: 'ตรวจความครบถ้วนและเวอร์ชันของเอกสาร แนบในแฟ้มคดี', parentIndex: 0 }, { title: 'ทนายตรวจร่างก่อนแจ้งลูกความ', days: 2, kind: 'APPROVAL', instructions: 'เปิดวงรอบตรวจเอกสารจากหน้าเอกสาร ก่อนอนุมัติหรือส่งออก', parentIndex: 1 }]],
  MEDICAL: ['รวบรวมหลักฐานเรื่องทางการแพทย์', [{ title: 'ตรวจหนังสือยินยอมและขอบเขตเวชระเบียน', days: 0, kind: 'APPROVAL', instructions: 'ให้ทนายตรวจสิทธิ์เข้าถึงและขอบเขตข้อมูลก่อนขอเวชระเบียน' }, { title: 'รวบรวมเวชระเบียนและค่าใช้จ่าย', days: 2, kind: 'DOCUMENT', instructions: 'แยกรายการรักษา วันที่ เอกสารค่าใช้จ่าย และเอกสารที่ยังขาด', parentIndex: 0 }, { title: 'ตรวจข้อเท็จจริงและประเด็นที่ต้องถามผู้เชี่ยวชาญ', days: 3, kind: 'TASK', instructions: 'ระบุข้อเท็จจริงที่มีแหล่งอ้างอิงและข้อที่ยังพิสูจน์ไม่ได้ ไม่สรุปความรับผิดล่วงหน้า', parentIndex: 1 }]],
  TRANSPORT: ['รวบรวมหลักฐานเรื่องขนส่ง', [{ title: 'ตรวจขอบเขตงานขนส่งและผู้เกี่ยวข้อง', days: 0, kind: 'TASK', instructions: 'ระบุผู้ว่าจ้าง ผู้ขนส่ง ผู้รับสินค้า และเอกสารสัญญา' }, { title: 'รวบรวมใบรับขน ใบส่งมอบ และหลักฐานความเสียหาย', days: 1, kind: 'DOCUMENT', instructions: 'บันทึกจุดรับ-ส่ง วันที่ สภาพสินค้า และข้อโต้แย้งจากเอกสารจริง', parentIndex: 0 }, { title: 'ทนายตรวจข้อเรียกร้องและร่างติดต่อคู่กรณี', days: 2, kind: 'APPROVAL', instructions: 'ตรวจสิทธิ์เรียกร้อง กำหนดที่เกี่ยวข้อง และอนุมัติร่างก่อนใช้', parentIndex: 1 }]],
};
export default function PlaybooksPage() {
  const { token, user } = useAuth(); const { locale } = useLocale(); const th = locale === 'th';
  const [items, setItems] = useState<PlaybookRelease[]>([]); const [name, setName] = useState(''); const [type, setType] = useState('GENERAL'); const [steps, setSteps] = useState<PlaybookStep[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const load = async () => { if (token) setItems(await setupRequest(token, '/playbooks')); };
  useEffect(() => { load().catch(e => setError(e.message)); }, [token]);
  const edit = (index: number, patch: Partial<PlaybookStep>) => setSteps(rows => rows.map((s, i) => i === index ? { ...s, ...patch } : s));
  return <div className="mx-auto max-w-4xl space-y-6"><header><h1 className="text-2xl font-semibold">Playbooks</h1><p className="mt-1 text-sm text-muted-foreground">{th ? 'ขั้นตอนงานที่สำนักงานตรวจแล้ว แต่ละรุ่นคงเดิม คดีที่ใช้รุ่นเก่าจะไม่ถูกเปลี่ยนเมื่อเผยแพร่รุ่นใหม่' : 'Reviewed office workflows. Published versions stay fixed; new releases never change existing cases.'}</p></header>{error && <p role="alert" className="text-destructive">{error}</p>}{notice && <p role="status">{notice}</p>}
    <section className="space-y-3"><h2 className="font-semibold">{th ? 'รุ่นที่เผยแพร่แล้ว' : 'Published versions'}</h2>{!items.length && <p className="text-sm text-muted-foreground">{th ? 'ยังไม่มี Playbook เริ่มจากตัวอย่างด้านล่างแล้วปรับให้ตรงวิธีทำงานของสำนักงาน' : 'No playbooks yet. Adapt a starter below to your office workflow.'}</p>}{items.map(p => <details key={p.id} className="rounded-lg border bg-card p-4"><summary className="cursor-pointer font-medium">{p.name} · v{p.version} · {p.workType}</summary><ol className="my-3 list-decimal space-y-2 pl-5 text-sm">{p.steps.map((s, i) => <li key={i}>{s.title} · +{s.days} {th ? 'วัน' : 'days'}<p className="text-xs text-muted-foreground">{s.instructions}</p></li>)}</ol>{user?.firmRole === 'OWNER' && <Button variant="outline" onClick={() => { setName(p.name); setType(p.workType); setSteps(structuredClone(p.steps)); }}>{th ? 'ใช้เป็นร่างรุ่นถัดไป' : 'Draft the next version'}</Button>}</details>)}</section>
    {user?.firmRole === 'OWNER' && <form className="space-y-4 rounded-xl border bg-card p-4 sm:p-6" onSubmit={async e => { e.preventDefault(); if (!token) return; setBusy(true); setError(''); try { const p = await setupRequest<PlaybookRelease>(token, '/playbooks', { name, workType: type, steps }); setNotice(`${p.name} v${p.version} · ${th ? 'เผยแพร่แล้ว' : 'Published'}`); setSteps([]); setName(''); await load(); } catch(e) { setError(e instanceof Error ? e.message : 'Failed'); } finally { setBusy(false); } }}><h2 className="text-lg font-semibold">{th ? 'ตรวจและเผยแพร่ขั้นตอนงาน' : 'Review and publish a workflow'}</h2><p className="text-xs text-muted-foreground">{th ? 'จำนวนวันเป็นเป้าหมายการทำงานของสำนักงาน ไม่ใช่การคำนวณอายุความ งานก่อนฟ้องยังอยู่ใน Intake จนยื่นฟ้องจริง' : 'Day offsets are office targets, not statutory deadlines. Pre-filing work remains in Intake until filing.'}</p><div className="flex flex-wrap gap-2">{Object.keys(starters).map(k => <Button key={k} type="button" variant="outline" onClick={() => { setType(k); setName(starters[k][0]); setSteps(structuredClone(starters[k][1])); }}>{k === 'GENERAL' ? (th ? 'ทั่วไป' : 'General') : k === 'MEDICAL' ? (th ? 'การแพทย์' : 'Medical') : (th ? 'ขนส่ง' : 'Transport')}</Button>)}</div>
      <label className="block text-sm">{th ? 'ชื่อ Playbook' : 'Playbook name'}<Input required maxLength={150} value={name} onChange={e => setName(e.target.value)} /></label>
      {steps.map((s, i) => <div key={i} className="space-y-2 rounded-lg border p-3"><label className="block text-sm">{i + 1}. {th ? 'งาน' : 'Task'}<Input required maxLength={200} value={s.title} onChange={e => edit(i, { title: e.target.value })} /></label><div className="grid gap-3 sm:grid-cols-3"><label className="block text-sm">{th ? 'เป้าหมายหลังเริ่ม (วัน)' : 'Days after start'}<Input type="number" min={0} max={365} value={s.days} onChange={e => edit(i, { days: Number(e.target.value) })} /></label><label className="block text-sm">{th ? 'ประเภทขั้นตอน' : 'Step type'}<select className="h-11 w-full rounded-lg border bg-background px-2" value={s.kind} onChange={e => edit(i, { kind: e.target.value as PlaybookStep['kind'] })}><option value="TASK">{th ? 'ทำงาน' : 'Task'}</option><option value="DOCUMENT">{th ? 'เตรียมเอกสาร' : 'Document'}</option><option value="APPROVAL">{th ? 'ตรวจและอนุมัติ' : 'Review and approval'}</option></select></label><label className="block text-sm">{th ? 'เป็นงานย่อยของ' : 'Subtask of'}<select className="h-11 w-full rounded-lg border bg-background px-2" value={s.parentIndex ?? ''} onChange={e => edit(i, { parentIndex: e.target.value === '' ? undefined : Number(e.target.value) })}><option value="">—</option>{steps.slice(0, i).map((p, j) => <option key={j} value={j}>{j + 1}. {p.title}</option>)}</select></label></div><label className="block text-sm">{th ? 'คำแนะนำและเอกสารที่ต้องใช้' : 'Instructions and required documents'}<textarea maxLength={5000} value={s.instructions} onChange={e => edit(i, { instructions: e.target.value })} className="min-h-20 w-full rounded-lg border bg-background p-2" /></label></div>)}
      <div className="flex flex-wrap gap-2"><Button type="button" variant="outline" disabled={steps.length >= 50} onClick={() => setSteps([...steps, { title: '', instructions: '', days: 0, kind: 'TASK' }])}>{th ? 'เพิ่มขั้นตอน' : 'Add step'}</Button>{steps.length > 0 && <Button type="button" variant="ghost" onClick={() => setSteps(steps.slice(0, -1))}>{th ? 'ลบขั้นตอนสุดท้าย' : 'Remove last step'}</Button>}<Button disabled={busy || !name.trim() || !steps.length || steps.some(s => !s.title.trim())}>{th ? 'ตรวจแล้ว เผยแพร่รุ่นนี้' : 'Reviewed — publish this version'}</Button></div>
    </form>}
    <Link className="inline-flex min-h-11 items-center text-primary underline" href="/cases">{th ? 'เลือกคดีแล้วใช้ Playbook ในหน้างาน →' : 'Choose a case and apply a playbook in Tasks →'}</Link>
  </div>;
}
