'use client';
import { useEffect, useRef, useState } from 'react';
import { Workroom, workroomRequest } from '@/lib/workroom-api';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useLocale } from '@/components/landing/LocaleProvider';
import { ThaiDateInput } from '@/components/ui/ThaiDateInput';

export function RequestWorkroom({ id, token, staff = false }: { id: string; token: string; staff?: boolean }) {
  const { locale } = useLocale(); const th = locale === 'th';
  const [data, setData] = useState<Workroom | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [body, setBody] = useState(''); const [file, setFile] = useState<File | null>(null); const input = useRef<HTMLInputElement>(null);
  const retryKey = useRef(''); const [scope, setScope] = useState(''); const [date, setDate] = useState(''); const [proposing, setProposing] = useState(false);
  const [deliverableId, setDeliverableId] = useState('');
  const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [handover, setHandover] = useState(false); const [shareConfirmed, setShareConfirmed] = useState(false);
  const load = async () => { const row = await workroomRequest<Workroom>(token, staff, `/${id}`); setData(row); };
  useEffect(() => { let active = true; setData(null); workroomRequest<Workroom>(token, staff, `/${id}`).then(r => { if (active) setData(r); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [token, staff, id]);
  async function run(fn: () => Promise<void>) { setBusy(true); setError(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : 'Failed'); } finally { setBusy(false); } }
  const fmt = (value: string | null) => value ? new Date(value).toLocaleDateString(th ? 'th-TH' : 'en-GB', { timeZone: 'Asia/Bangkok', day: 'numeric', month: 'short', year: 'numeric' }) : (th ? 'ยังไม่กำหนด' : 'Not set');
  return <section className="my-5 space-y-4 rounded-xl border bg-card p-4 sm:p-5" aria-label={th ? 'ห้องทำงานร่วมกัน' : 'Shared workroom'}>
    <div><h2 className="text-lg font-semibold">{th ? 'ห้องทำงานร่วมกัน' : 'Shared workroom'}</h2><p className="text-sm text-muted-foreground">{th ? 'ข้อความและไฟล์ในส่วนนี้มองเห็นร่วมกันกับลูกค้า การส่งคำขอยังไม่ถือว่าสำนักงานรับดำเนินการ' : 'Messages and files here are shared with the client. Submitting a request does not mean the office has accepted the engagement.'}</p></div>
    {error && <div role="alert" className="text-sm text-destructive">{error}<Button type="button" variant="ghost" onClick={() => run(load)}>{th ? 'โหลดใหม่' : 'Reload'}</Button></div>}
    {!data ? <p role="status">{th ? 'กำลังโหลด…' : 'Loading…'}</p> : <>
      <dl className="grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-muted-foreground">{th ? 'วันที่ลูกค้าขอ' : 'Client requested date'}</dt><dd>{fmt(data.requestedDate)}</dd></div><div><dt className="text-muted-foreground">{th ? 'วันที่สำนักงานเสนอ' : 'Office proposed date'}</dt><dd>{fmt(data.proposedDate)}</dd></div><div><dt className="text-muted-foreground">{th ? 'วันที่ตกลงร่วมกัน' : 'Agreed date'}</dt><dd className="font-semibold">{fmt(data.agreedDate)}</dd></div></dl>
      {data.scopeText && <div className="rounded-lg bg-muted p-3"><p className="text-sm font-semibold">{th ? `ขอบเขตงาน รุ่น ${data.commitmentVersion}` : `Scope, version ${data.commitmentVersion}`}</p><p className="whitespace-pre-wrap break-words text-sm">{data.scopeText}</p><p className="mt-2 text-xs text-muted-foreground">{data.owner} · {data.accepted ? (th ? 'ตกลงแล้ว' : 'Agreed') : (th ? 'รอลูกค้ายืนยัน' : 'Awaiting client acceptance')}</p></div>}
      {!staff && data.scopeText && !data.accepted && !data.withdrawn && <Button disabled={busy} className="min-h-11" onClick={() => run(async () => { await workroomRequest(token, false, `/${id}/accept`, { version: data.commitmentVersion }); await load(); })}>{th ? 'ยอมรับขอบเขตและวันที่ที่เสนอ' : 'Accept this scope and proposed date'}</Button>}
      {data.deliveredAt && <p role="status" className="rounded-md bg-muted p-3 text-sm">{th ? 'ส่งมอบงานแล้ว' : 'Work delivered'} · {fmt(data.deliveredAt)} · {data.deliveryAcknowledgedAt ? (th ? 'ลูกค้ายืนยันได้รับแล้ว' : 'Client acknowledged delivery') : (th ? 'รอยืนยันได้รับงาน' : 'Awaiting delivery acknowledgement')}</p>}
      {!staff && data.deliveredAt && !data.deliveryAcknowledgedAt && <Button disabled={busy} onClick={() => run(async () => { await workroomRequest(token, false, `/${id}/acknowledge-delivery`, { version: data.commitmentVersion }); await load(); })}>{th ? 'ยืนยันได้รับงานแล้ว' : 'Acknowledge delivery'}</Button>}
      <div className="space-y-3"><h3 className="font-medium">{th ? 'ข้อความและไฟล์ที่แบ่งปัน' : 'Shared messages and files'}</h3>{data.messages.length === 0 && <p className="text-sm text-muted-foreground">{th ? 'ส่งข้อมูลเพิ่มเติมหรือถามความคืบหน้าได้ที่นี่' : 'Add information or ask for an update here.'}</p>}
      {data.nextCursor && <Button variant="outline" disabled={busy} onClick={() => run(async () => { const older = await workroomRequest<Workroom>(token, staff, `/${id}?before=${data.nextCursor}`); setData({ ...data, nextCursor: older.nextCursor, messages: [...older.messages, ...data.messages] }); })}>{th ? 'โหลดข้อความก่อนหน้า' : 'Load earlier messages'}</Button>}
      <ol className="max-h-[32rem] space-y-3 overflow-y-auto">{data.messages.map(m => <li key={m.id} className="rounded-lg border p-3"><p className="text-xs font-medium text-muted-foreground">{m.authorKind === 'OFFICE' ? (th ? 'สำนักงาน' : 'Office') : m.authorKind === 'CLIENT' ? (th ? 'ลูกค้า' : 'Client') : (th ? 'บันทึกสถานะ' : 'Status record')} · {fmt(m.createdAt)}</p><p className="whitespace-pre-wrap break-words text-sm">{m.body}</p>{m.filename && <Button variant="link" className="h-auto min-h-11 max-w-full whitespace-normal break-all px-0 text-left" onClick={() => run(async () => { const blob = await workroomRequest<Blob>(token, staff, `/${id}/files/${m.id}`, undefined, true); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = m.filename!; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); })}>{m.filename} · {Math.ceil((m.size ?? 0) / 1024)} KB</Button>}</li>)}</ol></div>
      {!data.withdrawn && <form className="space-y-3 border-t pt-4" onSubmit={e => { e.preventDefault(); run(async () => { if (!retryKey.current) retryKey.current = crypto.randomUUID(); const form = new FormData(); form.set('requestKey', retryKey.current); form.set('body', body); if (file) form.set('file', file); await workroomRequest(token, staff, `/${id}/messages`, form); retryKey.current = ''; setBody(''); setFile(null); if (input.current) input.current.value = ''; await load(); }); }}>
        <label className="block text-sm">{th ? 'ข้อความเพิ่มเติม' : 'Add a message'}<textarea value={body} maxLength={10000} disabled={busy} onChange={e => { setBody(e.target.value); retryKey.current = ''; }} className="mt-1 min-h-24 w-full rounded-lg border bg-background p-3" /></label>
        <label className="block text-sm">{th ? 'แนบไฟล์ (ไม่เกิน 20 MB)' : 'Attach a file (up to 20 MB)'}<Input ref={input} type="file" disabled={busy} onChange={e => { const selected = e.target.files?.[0] ?? null; if (selected && selected.size > 20 * 1024 * 1024) { setError(th ? 'ไฟล์เกิน 20 MB' : 'File exceeds 20 MB'); e.target.value = ''; return; } setFile(selected); retryKey.current = ''; }} /></label>
        <Button type="submit" disabled={busy || (!body.trim() && !file)} className="min-h-11">{busy ? (th ? 'กำลังส่ง…' : 'Sending…') : (th ? 'ส่งข้อความและไฟล์' : 'Send message and file')}</Button>
      </form>}
      {staff && <div className="space-y-3 border-t pt-4"><div className="flex flex-wrap gap-2">{!data.deliveredAt && <Button variant="outline" onClick={() => { setProposing(!proposing); setScope(data.scopeText ?? ''); setDate(data.proposedDate?.slice(0,10) ?? ''); }}>{th ? 'เสนอขอบเขตและวันส่งมอบ' : 'Propose scope and delivery date'}</Button>}{data.accepted && !data.deliveredAt && <Button disabled={busy || !deliverableId} onClick={() => run(async () => { await workroomRequest(token, true, `/${id}/deliver`, { messageId: deliverableId }); await load(); })}>{th ? 'บันทึกส่งมอบงาน' : 'Mark delivered'}</Button>}<Button variant="ghost" onClick={() => setHandover(!handover)}>{th ? 'เปลี่ยนผู้ติดต่อของคำขอนี้' : 'Replace contact for this request'}</Button></div>
        {data.accepted && !data.deliveredAt && <label className="block text-sm">{th ? 'เลือกข้อความหรือไฟล์ที่ส่งมอบตามขอบเขตนี้' : 'Select the message or file that delivers this scope'}<select className="h-11 w-full rounded-lg border bg-background px-2" value={deliverableId} onChange={e => setDeliverableId(e.target.value)}><option value="">—</option>{data.messages.filter(m => m.authorKind === 'OFFICE').map(m => <option key={m.id} value={m.id}>{m.filename ?? m.body.slice(0, 100)}</option>)}</select></label>}
        {proposing && <form className="space-y-3" onSubmit={e => { e.preventDefault(); run(async () => { await workroomRequest(token, true, `/${id}/proposal`, { scopeText: scope, proposedDate: `${date}T00:00:00.000Z`, version: data.commitmentVersion }); setProposing(false); await load(); }); }}><label className="block text-sm">{th ? 'ขอบเขตงานและเงื่อนไข' : 'Scope and terms'}<textarea required maxLength={10000} value={scope} onChange={e => setScope(e.target.value)} className="min-h-24 w-full rounded-lg border bg-background p-3" /></label><label className="block text-sm">{th ? 'วันส่งมอบที่เสนอ' : 'Proposed delivery date'}<ThaiDateInput required value={date} onChange={setDate} /></label><Button disabled={busy || !scope.trim()}>{th ? 'ส่งข้อเสนอให้ลูกค้ายืนยัน' : 'Share proposal for client acceptance'}</Button></form>}
        {handover && <form className="space-y-3 rounded-lg border p-3" onSubmit={e => { e.preventDefault(); run(async () => { await workroomRequest(token, true, `/${id}/handover`, { fromContactId: from, toContactId: to }); setHandover(false); setShareConfirmed(false); await load(); }); }}><p className="text-sm">{th ? 'ผู้ติดต่อใหม่จะเห็นประวัติข้อความและไฟล์ในคำขอนี้ ผู้ติดต่อเดิมจะเข้าคำขอนี้ไม่ได้ ไม่เพิ่มสิทธิ์ดูคดีอื่นหรือร่างภายใน' : 'The replacement sees the shared history of this request. The previous contact loses request access. Other cases and internal drafts are not granted.'}</p><label className="block text-sm">{th ? 'ผู้ติดต่อเดิม' : 'Previous contact'}<select required value={from} onChange={e => setFrom(e.target.value)} className="h-11 w-full rounded-md border bg-background px-2"><option value="">—</option>{data.contacts.filter(c => data.contactIds?.includes(c.id)).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block text-sm">{th ? 'ผู้ติดต่อใหม่' : 'Replacement contact'}<select required value={to} onChange={e => setTo(e.target.value)} className="h-11 w-full rounded-md border bg-background px-2"><option value="">—</option>{data.contacts.filter(c => c.id !== from).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={shareConfirmed} onChange={e => setShareConfirmed(e.target.checked)} />{th ? 'ตรวจแล้ว ให้ประวัติเฉพาะคำขอนี้กับผู้ติดต่อใหม่' : 'I reviewed and grant only this request’s shared history.'}</label><Button disabled={busy || !from || !to || !shareConfirmed}>{th ? 'ยืนยันเปลี่ยนผู้ติดต่อ' : 'Confirm contact replacement'}</Button></form>}
      </div>}
    </>}
  </section>;
}
