#!/usr/bin/env node
/**
 * Turns docs/user-guide/slides.json (written by the Playwright guide suite)
 * into a self-contained slide deck at docs/user-guide/index.html.
 *
 *   node e2e/build-deck.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const GUIDE = path.resolve(HERE, '../docs/user-guide');
const slides = JSON.parse(fs.readFileSync(path.join(GUIDE, 'slides.json'), 'utf8'));

const esc = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/**
 * LINE OA is a chat bot, not a web page — Playwright can't screenshot a chat
 * the way it screenshots the app, so this section is hand-written from the
 * bot's actual source strings (apps/api/src/notifications/line-conversation)
 * instead of being generated by capture().
 */
const LINE_FLOWS = [
  {
    icon: '📋',
    name: 'สร้าง Case',
    command: 'พิมพ์ "สร้าง Case" หรือแตะปุ่มบนเมนูรูปภาพ',
    steps: [
      'บอทถาม "ชื่อเรื่อง/หัวข้อคดีคืออะไรครับ?" — พิมพ์หัวข้อคดี',
      '"ลูกความชื่ออะไรครับ? (พิมพ์ชื่อเพื่อค้นหา)" — พิมพ์ชื่อ บอทจะค้นในรายชื่อลูกค้าที่มีอยู่ให้เลือก หรือกด "ไม่เจอ" เพื่อใช้ชื่อที่พิมพ์ไปตรง ๆ',
      '"มีผู้รับผิดชอบร่วมไหมครับ? (เลือกได้หลายคน)" — เลือกทนาย/ผู้ช่วยที่ดูแลร่วม แล้วกด "พอแล้ว"',
      '"มีรายละเอียดเพิ่มเติมไหมครับ?" — พิมพ์รายละเอียดหรือกด "ไม่ระบุ"',
      'บอทสรุปข้อมูลทั้งหมดให้ตรวจ กด "ยืนยัน" เพื่อสร้างคดี หรือกดหัวข้อที่ต้องการแก้ก่อน',
    ],
  },
  {
    icon: '✅',
    name: 'เพิ่ม Task',
    command: 'พิมพ์ "เพิ่ม Task" หรือแตะปุ่มบนเมนูรูปภาพ',
    steps: [
      '"ชื่องานที่จะมอบหมายคืออะไรครับ?" — พิมพ์ชื่องาน',
      'บอทให้ "เลือกคดีครับ" — พิมพ์ชื่อ/เลขคดีเพื่อค้นหา หรือกด "นอกคดี" ถ้าเป็นงานที่ไม่ผูกกับคดีไหน',
      '"กำหนดส่ง" — เลือกวันครบกำหนด',
      '"มอบหมายให้ใครครับ?" — เลือกผู้รับผิดชอบ',
      'ตรวจสรุปแล้วกด "ยืนยัน" — งานจะไปโผล่ในหน้า งานที่ต้องทำ/รายละเอียดคดี ทันที',
    ],
  },
  {
    icon: '📝',
    name: 'สร้าง Todo',
    command: 'พิมพ์ "สร้าง Todo" หรือแตะปุ่มบนเมนูรูปภาพ',
    steps: [
      '"สร้าง Todo ใหม่ — ชื่องานคืออะไรครับ?" — พิมพ์ชื่องานส่วนตัว (ไม่ผูกกับคดี)',
      '"กำหนดส่ง" — เลือกวันครบกำหนด (ข้ามได้)',
      '"มอบหมายให้ใครครับ?" — ปกติจะเป็นตัวเอง หรือมอบให้คนอื่นได้',
      'กด "ยืนยัน" — ไปโผล่ในหน้า งานส่วนตัว (/todos) ของผู้รับ',
    ],
  },
  {
    icon: '💸',
    name: 'บันทึกค่าใช้จ่าย',
    command: 'พิมพ์ "บันทึกค่าใช้จ่าย" หรือแตะชิป "💸 ค่าใช้จ่าย" ใต้เมนู',
    steps: [
      '"จะกรอกเองหรือให้ AI อ่านจากรูปใบเสร็จครับ?" — เลือก "AI อ่านจากรูป" แล้วส่งรูปใบเสร็จ หรือเลือก "กรอกเอง"',
      'ถ้าส่งรูป AI จะอ่านยอดเงินให้อัตโนมัติ ถ้าอ่านไม่ได้บอทจะถามยอดเงินเอง',
      '"ค่าอะไรครับ? (เช่น ค่าส่งเอกสาร)" — พิมพ์รายละเอียดค่าใช้จ่าย',
      '"ผูกกับคดีไหนครับ?" — พิมพ์ชื่อคดีเพื่อค้นหา หรือกด "ข้าม" ถ้าเป็นค่าใช้จ่ายทั่วไปของสำนักงาน',
      'กด "ยืนยัน" — รายการจะเข้าไปเป็นสถานะร่างในหน้า ค่าใช้จ่าย (/expenses) รอส่งขออนุมัติ',
    ],
  },
  {
    icon: '💰',
    name: 'เบิกล่วงหน้า',
    command: 'พิมพ์ "เบิกล่วงหน้า" หรือแตะชิป "💰 เบิกล่วงหน้า" ใต้เมนู (เฉพาะเจ้าของสำนักงาน)',
    steps: [
      '"จ่ายเงินสำรองล่วงหน้าให้ใครครับ?" — เลือกสมาชิกในทีมที่จะรับเงินสำรอง',
      '"จำนวนเงินเท่าไหร่ครับ?" — พิมพ์จำนวนเงิน (ตัวเลขมากกว่า 0)',
      '"หมายเหตุครับ (หรือกด "ข้าม")" — ใส่เหตุผล/รายละเอียด',
      'กด "ยืนยัน" — ผู้รับจะได้ข้อความ LINE แจ้งทันทีว่า "💰 คุณได้รับเงินสำรองจ่าย…"',
    ],
  },
  {
    icon: '📊',
    name: 'งานของฉันวันนี้',
    command: 'พิมพ์ "งานของฉันวันนี้" ตรง ๆ หรือแตะชิป "📊 งานวันนี้" ใต้เมนู',
    steps: [
      'บอทตอบกลับสรุปนัดและงานที่ครบกำหนดวันนี้ทันที — เนื้อหาเดียวกับหน้า วันของฉัน (/my-day) บนเว็บ แต่ดูได้จากแชทโดยไม่ต้องเปิดแอป',
    ],
  },
];

const lineFlowHtml = (f) => `
      <div class="line-flow">
        <h4>${f.icon} ${esc(f.name)}</h4>
        <p class="line-cmd">${esc(f.command)}</p>
        <ol>${f.steps.map((s) => `<li>${esc(s)}</li>`).join('')}</ol>
      </div>`;

const lineSectionHtml = `
  <section class="slide" id="line-section">
    <header>
      <span class="num">LINE</span>
      <h2>ใช้งานผ่าน LINE — คุยกับบอทของสำนักงานแทนเปิดเว็บ</h2>
      <code>LINE Official Account</code>
    </header>
    <p class="desc">
      นอกจากเปิดเว็บ พนักงานยังสั่งงานผ่านแชท LINE OA ของสำนักงานได้เลย — สร้างคดี เพิ่มงาน บันทึกค่าใช้จ่าย
      หรือดูงานวันนี้ โดยพิมพ์คำสั่งหรือแตะปุ่มในแชท ไม่ต้องเปิดแอปเว็บก็ได้ ระบบยังส่งแจ้งเตือนนัดหมายล่วงหน้า
      3 วันก่อนถึงวันนัดให้ทาง LINE โดยอัตโนมัติหลังเชื่อมต่อบัญชีแล้ว
    </p>

    <div class="line-grid">
      <figure><img src="shots/line-home-menu.png" alt="เมนูหลักของ LINE OA" /></figure>
      <div>
        <h3>ขั้นตอนที่ 1 — เพิ่มเพื่อนและเชื่อมต่อบัญชี LINE (ทำครั้งเดียว)</h3>
        <p style="margin:0 0 10px; font-size:14px; color:#334155">
          ก่อนสั่งงานผ่านแชทได้ ต้องมี LINE Official Account ของสำนักงานก่อน (แอดมินตั้งค่า Channel ID/Secret ที่หน้า
          ตั้งค่า → การเชื่อมต่อ → LINE Messaging API — ถ้าเห็นข้อความ "ระบบ LINE ยังไม่ได้ตั้งค่า" แปลว่ายังไม่มีใครตั้งค่าส่วนนี้
          ต้องให้แอดมินไปสร้าง Channel ใน LINE Developers Console ก่อน แล้วกรอก Channel ID/Secret/Access Token)
        </p>
        <ol class="line-link-steps">
          <li>เข้าเว็บแอป ไปที่หน้า <b>ตั้งค่า</b> (/settings) → หัวข้อ <b>การเชื่อมต่อ</b> → กดปุ่ม <b>"เชื่อมต่อ LINE"</b> ใต้หัวข้อ "เชื่อมต่อ LINE ส่วนตัว" (ดูสไลด์ 23 — ตั้งค่า)</li>
          <li>หน้าจะแสดง <b>"1. เพิ่มเพื่อน Official Account [ที่นี่]"</b> — กดลิงก์นี้เพื่อเปิด LINE แล้วกด <b>Add friend</b> เพิ่มบัญชีสำนักงานเป็นเพื่อน (ถ้าเพิ่มเพื่อนไว้แล้วข้ามขั้นนี้ได้เลย)</li>
          <li>กลับมาที่เว็บ จะเห็น <b>"2. ส่งรหัสด้านล่างในแชท LINE"</b> พร้อมรหัสรูปแบบ <code>LF-XXXXXX</code> (กด "คัดลอก" ได้) — รหัสมีอายุ 15 นาที ถ้าหมดอายุกด "สร้างรหัสใหม่"</li>
          <li>เปิดแชท LINE Official Account ที่เพิ่งเพิ่มเพื่อน แล้วพิมพ์/วางรหัสนั้นส่งเข้าไปในแชท</li>
          <li>บอทตอบ <i>"✅ เชื่อมต่อสำเร็จ! สวัสดีคุณ …คุณจะได้รับแจ้งเตือนนัดหมายล่วงหน้า 3 วันก่อนถึงวันนัด"</i> — เสร็จแล้ว ใช้งานได้ทันที</li>
        </ol>
        <h3>เมนูหลัก</h3>
        <p>ทักบอทด้วยคำว่า <b>"เมนู"</b> เมื่อไหร่ก็ได้เพื่อกลับมาที่เมนูรูปภาพด้านบน (3 ปุ่มที่เห็นในรูป: สร้าง Case /
        เพิ่ม Task / สร้าง Todo) และมีปุ่มลัดเพิ่มเติมใต้เมนูอีก 3 ปุ่ม: 💸 ค่าใช้จ่าย, 💰 เบิกล่วงหน้า, 📊 งานวันนี้</p>
        <p>ระหว่างทำรายการค้างอยู่ พิมพ์ <b>"เมนู"</b> เพื่อกลับหน้าแรก หรือ <b>"ยกเลิก"</b> เพื่อเลิกทำรายการนั้นได้ทุกเมื่อ</p>
      </div>
    </div>

    <h3 style="margin-top:24px">ขั้นตอนที่ 2 — ใช้แต่ละคำสั่ง</h3>
    <div class="line-flows">${LINE_FLOWS.map(lineFlowHtml).join('')}</div>
  </section>`;

const slideHtml = (s, i) => `
  <section class="slide" id="slide-${i + 1}" data-index="${i + 1}">
    <header>
      <span class="num">${i + 1} / ${slides.length}</span>
      <h2>${esc(s.title)}</h2>
      <code>${esc(s.route)}</code>
    </header>
    <p class="desc">${esc(s.description)}</p>
    <ol class="callouts">
      ${s.callouts.map((c) => `<li><span class="pin">${c.n}</span>${esc(c.label)}</li>`).join('\n      ')}
    </ol>
    <figure><img src="shots/${esc(s.file)}" alt="${esc(s.title)}" /></figure>
  </section>`;

const html = `<!doctype html>
<html lang="th">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Samnuan — คู่มือการใช้งาน</title>
<style>
  :root { --red:#e11d48; --ink:#0f172a; --muted:#64748b; --line:#e2e8f0; --bg:#f8fafc; }
  * { box-sizing:border-box }
  body { margin:0; background:var(--bg); color:var(--ink);
         font:16px/1.6 "Noto Sans Thai",Sarabun,-apple-system,system-ui,sans-serif }
  .wrap { max-width:1100px; margin:0 auto; padding:32px 20px 80px }
  .cover { background:#fff; border:1px solid var(--line); border-radius:18px; padding:40px; margin-bottom:28px }
  .cover h1 { margin:0 0 8px; font-size:32px }
  .cover p { margin:0; color:var(--muted) }
  .toc { display:grid; grid-template-columns:repeat(auto-fill,minmax(240px,1fr)); gap:8px; margin-top:24px }
  .toc a { display:block; padding:10px 12px; background:var(--bg); border:1px solid var(--line);
           border-radius:10px; text-decoration:none; color:var(--ink); font-size:14px }
  .toc a:hover { border-color:var(--red); color:var(--red) }
  .slide { background:#fff; border:1px solid var(--line); border-radius:18px; padding:28px;
           margin-bottom:28px; scroll-margin-top:20px }
  .slide header { display:flex; align-items:baseline; gap:12px; flex-wrap:wrap; border-bottom:2px solid var(--red);
                  padding-bottom:12px; margin-bottom:16px }
  .num { background:var(--red); color:#fff; border-radius:999px; padding:3px 11px; font-size:13px; font-weight:700 }
  .slide h2 { margin:0; font-size:22px; flex:1 }
  .slide code { color:var(--muted); font-size:13px }
  .desc { margin:0 0 16px; color:#334155 }
  .callouts { margin:0 0 20px; padding:0; list-style:none; display:grid; gap:8px;
              grid-template-columns:repeat(auto-fill,minmax(280px,1fr)) }
  .callouts li { display:flex; align-items:flex-start; gap:9px; font-size:14px; background:var(--bg);
                 border:1px solid var(--line); border-radius:10px; padding:8px 11px }
  .pin { flex:none; width:22px; height:22px; border-radius:999px; background:var(--red); color:#fff;
         font-size:12px; font-weight:700; display:grid; place-items:center }
  figure { margin:0; border:1px solid var(--line); border-radius:12px; overflow:hidden }
  figure img { display:block; width:100%; height:auto }
  .line-grid { display:grid; grid-template-columns:280px 1fr; gap:24px; align-items:start }
  .line-grid figure { max-width:280px }
  .line-link-steps { margin:0 0 20px; padding-left:20px; display:grid; gap:6px; font-size:14px; color:#334155 }
  .line-flows { display:grid; grid-template-columns:repeat(auto-fill,minmax(320px,1fr)); gap:14px }
  .line-flow { background:var(--bg); border:1px solid var(--line); border-radius:12px; padding:14px 16px }
  .line-flow h4 { margin:0 0 6px; font-size:15px }
  .line-cmd { margin:0 0 8px; font-size:13px; color:var(--muted) }
  .line-flow ol { margin:0; padding-left:18px; display:grid; gap:5px; font-size:13.5px; color:#334155 }
  @media (max-width:700px) { .line-grid{grid-template-columns:1fr} }
  @media print {
    body { background:#fff }
    .wrap { max-width:none; padding:0 }
    .cover { border:none; border-radius:0; page-break-after:always }
    .slide { page-break-after:always; page-break-inside:avoid; border:none; border-radius:0 }
    .toc a { border-color:#cbd5e1 }
  }
</style>
</head>
<body>
<div class="wrap">
  <div class="cover">
    <h1>Samnuan — คู่มือการใช้งานทีละหน้าจอ</h1>
    <p>ภาพหน้าจอทั้งหมดถูกถ่ายอัตโนมัติด้วย Playwright จากระบบจริง กรอบและป้ายสีแดงคือจุดที่ต้องกด/กรอกในแต่ละหน้า
    ส่วนท้ายเล่มมีวิธีใช้งานผ่านแชท LINE Official Account เพิ่มเติม</p>
    <nav class="toc">
      ${slides.map((s, i) => `<a href="#slide-${i + 1}">${i + 1}. ${esc(s.title)}</a>`).join('\n      ')}
      <a href="#line-section">LINE. ใช้งานผ่าน LINE</a>
    </nav>
  </div>
  ${slides.map(slideHtml).join('\n')}
  ${lineSectionHtml}
</div>
</body>
</html>`;

fs.writeFileSync(path.join(GUIDE, 'index.html'), html);
console.log(`built ${path.join(GUIDE, 'index.html')} — ${slides.length} slides`);
