'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/lib/auth';
import { useLocale } from '@/components/landing/LocaleProvider';
import { ImportPreview, parseImportCsv, setupRequest, SetupProgress } from '@/lib/practice-setup';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
export default function GettingStarted() {
  const { user, token } = useAuth(); const { locale } = useLocale(); const th = locale === 'th';
  const [progress, setProgress] = useState<SetupProgress | null>(null); const [csv, setCsv] = useState('clientName,caseRef,caseTitle\n'); const [preview, setPreview] = useState<ImportPreview | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState('');
  const load = async () => { if (token) setProgress(await setupRequest(token, '/progress')); };
  useEffect(() => { if (token && user?.firmRole === 'OWNER') load().catch(e => setError(e.message)); }, [token, user?.firmRole]);
  async function run(fn: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await fn(); } catch(e) { setError(e instanceof Error ? e.message : 'Failed'); } finally { setBusy(false); } }
  if (user?.firmRole !== 'OWNER') return <p>{th ? 'ส่วนนี้สำหรับเจ้าของสำนักงาน' : 'This page is for the firm owner.'}</p>;
  return <div className="mx-auto max-w-4xl space-y-6"><header><h1 className="text-2xl font-semibold">{th ? 'เริ่มใช้งานสำนักงาน' : 'Set up your office'}</h1><p className="mt-1 text-sm text-muted-foreground">{th ? 'ความคืบหน้าอ้างอิงจากข้อมูลจริง เริ่มด้วยทีม ลูกความ และคดีแรก' : 'Progress comes from real records. Start with your team, clients and first case.'}</p></header>
    {error && <p role="alert" className="text-destructive">{error}</p>}{notice && <p role="status" className="rounded-lg bg-muted p-3">{notice}</p>}
    {progress && <div className="grid gap-3 sm:grid-cols-3">{[{ title: th ? 'ทีมงาน' : 'Team', count: progress.members, done: progress.members > 1, href: '/team', hint: th ? `คำเชิญรอตอบ ${progress.invites}` : `${progress.invites} pending invitations` }, { title: th ? 'ลูกความ' : 'Clients', count: progress.clients, done: progress.clients > 0, href: '/clients', hint: th ? 'เพิ่มทีละรายหรือนำเข้าด้านล่าง' : 'Add one or import below' }, { title: th ? 'คดี' : 'Cases', count: progress.cases, done: progress.cases > 0, href: '/cases', hint: th ? 'เปิดคดีแรกแล้วใช้ Playbook' : 'Open a case and apply a playbook' }].map(s => <Link key={s.href} href={s.href} className="rounded-xl border bg-card p-4"><p className="font-medium">{s.done ? '✓ ' : ''}{s.title} · {s.count}</p><p className="mt-1 text-xs text-muted-foreground">{s.hint}</p></Link>)}</div>}
    <section className="space-y-4 rounded-xl border bg-card p-4 sm:p-6"><h2 className="text-lg font-semibold">{th ? 'นำเข้าลูกความและคดีจาก CSV' : 'Import clients and cases from CSV'}</h2><p className="text-sm text-muted-foreground">{th ? 'ไม่เกิน 200 แถว ชื่อลูกความเดิมจะใช้รายเดิม เลขคดีซ้ำจะหยุดให้แก้ไข ถ้าต้องการเพิ่มเฉพาะลูกความ เว้นสองช่องคดีว่างได้' : 'Up to 200 rows. Existing client names are reused; duplicate case references must be corrected. Leave both case columns blank to import clients only.'}</p>
      <Button variant="outline" onClick={() => { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob(['\uFEFFclientName,caseRef,caseTitle\nตัวอย่างลูกความ,DEMO-001,ตัวอย่างชื่อคดี\n'], { type: 'text/csv;charset=utf-8' })); a.download = 'samnuan-import-template.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000); }}>{th ? 'ดาวน์โหลดตัวอย่าง CSV' : 'Download CSV template'}</Button>
      <label className="block text-sm">{th ? 'เลือกไฟล์ CSV (UTF-8)' : 'Choose a CSV file (UTF-8)'}<Input type="file" accept=".csv,text/csv" disabled={busy} onChange={e => { const file = e.target.files?.[0]; if (!file) return; if (file.size > 1024 * 1024) { setError(th ? 'ไฟล์ใหญ่เกิน 1 MB' : 'File exceeds 1 MB'); return; } file.text().then(text => { setCsv(text); setPreview(null); }); }} /></label>
      <label className="block text-sm">{th ? 'ตรวจหรือแก้ไขข้อมูลก่อนนำเข้า' : 'Review or edit before importing'}<textarea spellCheck={false} value={csv} onChange={e => { setCsv(e.target.value); setPreview(null); }} className="mt-1 min-h-36 w-full rounded-lg border bg-background p-3 font-mono text-sm" /></label>
      <Button className="min-h-11" disabled={busy} onClick={() => token && run(async () => { setPreview(await setupRequest<ImportPreview>(token, '/imports/preview', { rows: parseImportCsv(csv) })); })}>{th ? 'ตรวจตัวอย่างก่อนบันทึก' : 'Preview before importing'}</Button>
      {preview && <div className="space-y-3"><h3 className="font-medium">{th ? `ตัวอย่าง ${preview.rows.length} แถว` : `${preview.rows.length} preview rows`}</h3><ol className="max-h-96 space-y-2 overflow-y-auto">{preview.rows.map(r => <li key={r.row} className="rounded-lg border p-3 text-sm"><strong>{r.row}. {r.clientName || '—'}</strong><p className="break-words">{r.caseRef} · {r.caseTitle}</p><p className="text-xs text-muted-foreground">{r.existingClientId ? (th ? 'ใช้ลูกความเดิม' : 'Reuse existing client') : (th ? 'เพิ่มลูกความใหม่ (ชื่อซ้ำในชุดเดียวกันรวมเป็นรายเดียว)' : 'Create client; matching names in this batch share one record')}</p>{r.errors.map(e => <p key={e} className="text-destructive">{e}</p>)}</li>)}</ol><Button disabled={busy || !preview.canCommit} className="min-h-11" onClick={() => token && run(async () => { await setupRequest(token, `/imports/${preview.id}/commit`, {}); setPreview(null); setNotice(th ? 'นำเข้าแล้ว ตรวจข้อมูลได้ที่ลูกความและคดี' : 'Imported. View records in Clients and Cases.'); await load(); })}>{th ? 'ยืนยันนำเข้าข้อมูลชุดนี้' : 'Confirm this import'}</Button></div>}
    </section>
    <section className="space-y-3"><h2 className="font-semibold">{th ? 'ประวัติการนำเข้า' : 'Import history'}</h2><p className="text-sm text-muted-foreground">{th ? 'ยกเลิกได้เฉพาะข้อมูลที่ชุดนี้สร้างและยังไม่ถูกแก้ไขหรือใช้ต่อ ระบบจะไม่ลบข้อมูลชุดอื่น' : 'Undo removes only records created by that batch, if unchanged and unused.'}</p>{progress?.batches.map(b => <div key={b.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><p className="text-sm">{new Date(b.createdAt).toLocaleString(th ? 'th-TH' : 'en-GB')} · {b.status}</p>{b.status === 'COMMITTED' && <Button variant="outline" disabled={busy} onClick={() => { if (!confirm(th ? 'ยกเลิกข้อมูลที่นำเข้าจากชุดนี้?' : 'Undo the records created by this batch?')) return; if (token) run(async () => { await setupRequest(token, `/imports/${b.id}/undo`, {}); setNotice(th ? 'ยกเลิกชุดนำเข้าแล้ว' : 'Import undone'); await load(); }); }}>{th ? 'ยกเลิกชุดนำเข้านี้' : 'Undo this batch'}</Button>}</div>)}</section>
    <Link href="/playbooks" className="inline-flex min-h-11 items-center text-primary underline">{th ? 'จัดขั้นตอนงานด้วย Playbook →' : 'Set up workflow playbooks →'}</Link>
  </div>;
}
