ALTER TYPE "CaseStage" ADD VALUE IF NOT EXISTS 'ANSWER' AFTER 'FILING';
ALTER TYPE "CaseStage" ADD VALUE IF NOT EXISTS 'APPEAL' AFTER 'CLOSING';
ALTER TYPE "CaseStage" ADD VALUE IF NOT EXISTS 'SUPREME' AFTER 'APPEAL';
