'use client';
import { useEffect, useState } from 'react';
import { useAuth } from '@/lib/auth';
import { useLocale } from '@/components/landing/LocaleProvider';
import { PlaybookPreview, PlaybookRelease, setupRequest } from '@/lib/practice-setup';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
export function CasePlaybook({ caseId, onApplied }: { caseId: string; onApplied: () => void }) {
  const { token } = useAuth(); const { locale } = useLocale(); const th = locale === 'th';
  const [releases, setReleases] = useState<PlaybookRelease[]>([]); const [releaseId, setReleaseId] = useState(''); const [start, setStart] = useState(new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Bangkok' })); const [preview, setPreview] = useState<PlaybookPreview | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [applied, setApplied] = useState(false);
  useEffect(() => { if (token) setupRequest<PlaybookRelease[]>(token, '/playbooks').then(setReleases).catch(e => setError(e.message)); }, [token]);
  return <details className="mb-4 rounded-xl border bg-card p-4"><summary className="cursor-pointer font-medium">{th ? 'เริ่มงานจาก Playbook' : 'Start from a playbook'}</summary><div className="mt-3 space-y-3"><p className="text-xs text-muted-foreground">{th ? 'สร้างงานจริงให้ทนายหลักของคดี ตรวจวันก่อนยืนยัน สามารถเปลี่ยนผู้รับผิดชอบในแต่ละงานได้' : 'Creates tasks for the case’s lead lawyer. Review dates before applying; reassign individual tasks afterward.'}</p>{error && <p role="alert" className="text-destructive">{error}</p>}{applied && <p role="status">{th ? 'เพิ่มงานจาก Playbook แล้ว' : 'Playbook tasks added'}</p>}<label className="block text-sm">Playbook<select value={releaseId} onChange={e => { setReleaseId(e.target.value); setPreview(null); setApplied(false); }} className="h-11 w-full rounded-lg border bg-background px-2"><option value="">{th ? 'เลือกรุ่น' : 'Choose a version'}</option>{releases.map(r => <option key={r.id} value={r.id}>{r.name} · v{r.version} · {r.workType}</option>)}</select></label><label className="block text-sm">{th ? 'วันที่เริ่ม' : 'Start date'}<Input type="date" value={start} onChange={e => { setStart(e.target.value); setPreview(null); }} /></label>{preview && <ol className="list-decimal space-y-2 pl-5 text-sm">{preview.steps.map((s, i) => <li key={i}>{s.title} · {new Date(s.dueAt).toLocaleDateString(th ? 'th-TH' : 'en-GB', { timeZone: 'Asia/Bangkok' })}<p className="text-xs text-muted-foreground">{s.instructions}</p></li>)}</ol>}{preview?.existing && <p>{th ? 'คดีนี้ใช้รุ่นนี้แล้ว จะไม่เพิ่มงานซ้ำ' : 'This version is already applied; no duplicate tasks will be created.'}</p>}<Button disabled={busy || !releaseId || !start || !!preview?.existing || applied} onClick={async () => { if (!token) return; setBusy(true); setError(''); try { const payload = { releaseId, startDate: `${start}T00:00:00+07:00` }; if (!preview) setPreview(await setupRequest(token, `/cases/${caseId}/preview`, payload)); else { await setupRequest(token, `/cases/${caseId}/apply`, payload); setApplied(true); onApplied(); } } catch(e) { setError(e instanceof Error ? e.message : 'Failed'); } finally { setBusy(false); } }}>{preview ? (th ? 'ยืนยันเพิ่มงานตามรายการ' : 'Confirm these tasks') : (th ? 'ดูงานและวันก่อนเพิ่ม' : 'Preview tasks and dates')}</Button></div></details>;
}
